### ISSUE TITLE
Make `bolt-sidecar` package a Cargo workspace

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#706]
Currently the `bolt-sidecar` is one big crate. As the project is becoming more and more mature there are some components (like the primitives) that should become separate crates so that can be used by other projects as dependency.

For a guideline, every folder under `bolt-sidecar/src` could become a separate crate.

**Comment by mempirate** [comment]
Would start with just `bolt-common` and `bolt-primitives`, i.e. the once we know would be used by other projects like registry, RPC etc.

**Comment by 0ex-d** [comment]
What do you think of workspace dependency alias? I can work on this, incrementally move `src/common` -> `crates/common`.

```toml
[workspace.dependencies]
bolt-common = { path = "./crates/common" }
bolt-primitives = { path = "./crates/primitives" }
```
